[package]
name = "fighting-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
shuttle-rocket = "0.35.0"
shuttle-runtime = "0.35.0"
shuttle-shared-db = { version = "0.35.2", features = ["postgres"] }
sqlx = "0.7.3"
tokio = "1.26.0"
